### ISSUE TITLE
AtomicQueryV3

### ISSUE THREAD

**Issue by nickz-t3** [iden3/circuits#130]
where can I find the circuit for AtomicQueryV3

**Comment by nickz-t3** [comment]
To be more precise I need the wasm file for this https://github.com/0xPolygonID/js-sdk/blob/main/src/circuits/atomic-query-v3.ts

**Comment by OBrezhniev** [comment]
Hi @nickz-t3! You can find it in this archive: http://iden3-circuits-bucket.s3.eu-west-1.amazonaws.com/latest.zip
