### ISSUE TITLE
Review of circuits/idState.circom

### ISSUE THREAD

**Issue by ed255** [iden3/circuits#6]
Here's a review of `circuits/idState.circom`.

Checking that `newIdState != 0` is done twice:
https://github.com/iden3/circuits/blob/512a451f6b1d9966fc6917ae130ef6f992485af7/circuits/idState.circom#L54-L57
https://github.com/iden3/circuits/blob/512a451f6b1d9966fc6917ae130ef6f992485af7/circuits/idState.circom#L64-L67

The rest looks good and matches the design we discussed!

**Comment by arnaucube** [comment]
true! fixed in #7 , using directly `IsZero` as `IsEqual` internally uses `IsZero`
