### ISSUE TITLE
Can LessThan254 template be simplified?

### ISSUE THREAD

**Issue by nedgar** [iden3/circuits#92]
In the comparators, the `LessThan254` template has a `component hiBitGt = GreaterThan(4)` for comparing the high two bits (not four) but it looks like this is redundant. The output is calculated as `out <== (hiBitEq.out * lt.out) + (hiBitLt.out * 1) + (hiBitGt.out * 0)`, where `hiBitGt.out * 0` will always be 0. Can this be simplified to just: `out <== (hiBitEq.out * lt.out) + (hiBitLt.out * 1)`?

FYI @OBrezhniev

**Comment by nedgar** [comment]
FYI @vmidyllic

**Comment by vmidyllic** [comment]
@OBrezhniev

**Comment by OBrezhniev** [comment]
@vmidyllic I talked with @nedgar on that matter. I will take a look on this in scope of coming circuit improvements.
