### ISSUE TITLE
Can the verifyCredentialSubject* templates be simplified to not use getClaimHeader()?

### ISSUE THREAD

**Issue by nedgar** [iden3/circuits#95]
The [verifyCredentialSubject](https://github.com/iden3/circuits/blob/8fffb6609ecad0b7bcda19bb908bdb544bdb3cf7/circuits/lib/utils/claimUtils.circom#L180) and [verifyCredentialSubjectProfile](https://github.com/iden3/circuits/blob/8fffb6609ecad0b7bcda19bb908bdb544bdb3cf7/circuits/lib/utils/claimUtils.circom#L196) templates use the `getClaimHeader()` template, but neither of its outputs are used, and it doesn't look like it adds any meaningful constraints. Is it required?

FYI @OBrezhniev

**Comment by nedgar** [comment]
Also wondering if the unused constraints would get optimized out.

**Comment by OBrezhniev** [comment]
We'll check.
From circom perspective there's no notion of unused constraints. Compiler only distinguishes between linear and quadratic constraints, and can remove some linear ones.

**Comment by OBrezhniev** [comment]
Template rewritten
